LABEL_MAP = {
    "apostrophe(')": "apos",
    "(.)": "dot",
    "bracketclose(])": "bracketclose",
    "bracketopen([)": "bracketopen",
    "]": "bracketclose",
    "[": "bracketopen",
    "comma(,)": "comma",
    "equal(=)": "equal",
    "=": "equal",
    ";": "semicolon",
    "del": "delete",
    ",": "comma",
    "-": "dash",
}

DATASET_CONFIG = {
    "mka": {
        "num_segmentation_tries": 1000,
        "num_keystrokes": 30,
        "initial_step": 0.003,
        "min_stroke_length": 180,
        "overlap_rate": 0.12,
        "steps": {
            "Lctrl": 0.002,
            "f": 0.003,
            "p": 0.003,
            "v": 0.0035,
        },
        "thresholds": {
            "Lctrl": 0.5,
            "f": 0.38,
            "p": 0.3,
            "v": 0.3,
        },
        "initial_threshold": 0.4,
        "before": 3000,
        "after": 5000,
        "last_strokes_to_skip": {
            "rshift": [-1],
            "lalt": [-1],
            "tab": [-1],
            "1": [-1],
            "b": [-1],
        },
        "keystrokes_to_skip": {
            "Lctrl": [13, 21],
            "m": [19],
            "n": [0],
            "o": [0],
            "ralt": [0],
            "u": [0, 12],
            "p": [0, 9, 11, 12, 13, 19],
            "f": [0],
            "3": [13],
            "4": [28],
            "5": [15],
            "6": [6],
            "e": [0],
            "lalt": [3],
            "lcmd": [0],
            "left": [0],
            "s": [2],
            "t": [14],
            "up": [12],
            "w": [27],
            "y": [17],
        },
    },
    "practical": {
        "num_segmentation_tries": 300,
        "num_keystrokes": 25,
        "initial_step": 0.006,
        "initial_threshold": 0.03,
        "before": 10000,
        "after": 10000,
        "min_stroke_length": 600,
        "overlap_rate": 0.12,
        "keystrokes_to_skip": {
            "h": [0],
            "9": [0],
            "6": [0],
            "u": [0],
            "0": [0],
        },
        "last_strokes_to_skip": {
            "j": [-1],
            "n": [-1],
            "a": [-1],
            "c": [-1],
        },
    },
    "custom_mac": {
        "num_segmentation_tries": 300,
        "num_keystrokes": 15,
        "initial_step": 0.02,
        "initial_threshold": 0.2,
        "before": 5000,
        "after": 4000,
        "min_stroke_length": 1000,
        "overlap_rate": 0.12,
        "keystrokes_to_skip": {
            "6": [13],
            "9": [4],
            "bracketclose": [2, 11],
            "ctrl": [2, 4, 13],
            "dot": [8],
            "ralt": [12],
            "up": [4, 5, 7, 10, 14],
            "g": [13],
            "delete": [11, 12],
            "slash": [10, 12, 13],
            "rcmd": [11],
            "p": [8, 9],
        },
        "last_strokes_to_skip": {
            "apos": [-1],
            "dash": [-1],
            "p": [-1],
        },
        "overlap_rates": {
            "delete": -0.05,
            "h": 0.06,
            "left": -0.12,
            "p": -0.05,
            "rcmd": -0.2,
            "slash": -0.1,
        },
    },
    "custom_dishwasher": {
        "num_segmentation_tries": 300,
        "num_keystrokes": 15,
        "initial_step": 0.02,
        "initial_threshold": 0.2,
        "before": 5000,
        "after": 4000,
        "min_stroke_length": 1000,
        "overlap_rate": 0.12,
        "keystrokes_to_skip": {
            "9": [2, 12],
            "backslash": [7, 6, 5, 10],
            "dash": [12],
            "delete": [4],
            "lshift": [11, 12],
            "m": [8],
            "n": [5, 7],
            "r": [0],
            "o": [7],
            "dot": [6, 9, 12],
            "equal": [0, 9, 10, 12, 13],
            "up": [8],
        },
        "last_strokes_to_skip": {
            "lshift": [-1],
            "t": [-1],
            "right": [-1],
        },
        "overlap_rates": {
            "8": -0.1,
            "bracketopen": -0.06,
            "dot": -0.06,
            "equal": -0.09,
            "o": 0.0,
            "right": -0.05,
            "up": -0.02,
        },
    },
    "custom_washing_machine": {
        "num_segmentation_tries": 300,
        "num_keystrokes": 15,
        "initial_step": 0.02,
        "initial_threshold": 0.2,
        "before": 5000,
        "after": 5000,
        "min_stroke_length": 1000,
        "overlap_rate": 0.05,
        "keystrokes_to_skip": {
            "0": [3],
            "backslash": [12, 13],
            "bracketclose": [2, 3],
            "ctrl": [5],
            "dash": [9],
            "down": [12],
            "enter": [9],
            "equal": [12],
            "g": [0],
            "i": [5, 9, 11],
            "j": [5, 7],
            "lcmd": [11],
            "n": [4, 8],
            "left": [4, 5, 13],
            "ralt": [13],
            "rcmd": [2, 5],
            "right": [3, 10],
            "up": [4, 5, 8, 10],
        },
        "last_strokes_to_skip": {
            "0": [-1],
            "backslash": [-1],
            "i": [-1],
        },
        "overlap_rates": {
            "bracketclose": 0.07,
            "i": -0.17,
            "j": -0.06,
            "lcmd": -0.08,
            "lshift": -0.09,
            "n": -0.15,
            "rcmd": -0.17,
        },
    },
    "custom_open_window": {
        "num_segmentation_tries": 300,
        "num_keystrokes": 15,
        "initial_step": 0.02,
        "initial_threshold": 0.2,
        "before": 5000,
        "after": 5500,
        "min_stroke_length": 1000,
        "overlap_rate": -0.1,
        "overlap_rates": {
            # '0': -0.1,
            # '1': -0.1,
            # '2': -0.1,
            # '3': -0.1,
            # '4': -0.1,
            "5": -0.14,
            # '6': -0.1,
            "b": -0.2,
            "backslash": -0.15,
            "bracketclose": -0.15,
            "bracketopen": -0.15,
            "comma": -0.12,
            "equal": -0.06,
            "esc": -0.15,
            "lcmd": -0.05,
            "rcmd": -0.2,
            "slash": -0.2,
            "t": -0.05,
        },
        "keystrokes_to_skip": {
            "0": [2, 3, 7],
            "1": [0],
            "2": [1],
            "3": [12, 13],
            "4": [5],
            "6": [13],
            "5": [0, 3, 6, 7, 8],
            "7": [5, 6, 12],
            "8": [5],
            "9": [10, 11],
            "a": [4],
            "apos": [11, 13],
            "b": [3, 4],
            "backslash": [1, 7, 8, 13],
            "caps": [2, 3],
            "comma": [0, 2, 4, 7],
            "d": [11],
            "dash": [4],
            "delete": [12],
            "dot": [8, 9, 10],
            "down": [7, 12],
            "e": [3],
            "enter": [6, 10],
            "equal": [0, 2, 9],
            "esc": [0, 4],
            "g": [5, 13],
            "h": [6, 13],
            "i": [1, 9],
            "j": [4],
            "left": [9, 12],
            "m": [4],
            "n": [9],
            "o": [8],
            "p": [4, 10],
            "q": [8],
            "r": [13],
            "ralt": [2, 7],
            "rcmd": [10, 13],
            "right": [0, 6, 9, 12],
            "rshift": [0, 10],
            "s": [4, 8],
            "semicolon": [5, 7],
            "slash": [1, 5, 10],
            "space": [10],
            "t": [5, 7, 9],
            "tab": [9],
            "u": [8],
            "w": [13],
            "y": [8],
        },
        "last_strokes_to_skip": {
            "9": [-1],
            "backslash": [-1],
            "equal": [-1],
            "f": [-1],
            "h": [-1],
            "lalt": [-1],
            "space": [-1],
        },
    },
}
