LABEL_MAP = {
    "apostrophe(')": 'apos',
    '(.)': 'dot',
    'bracketclose(])': 'bracketclose',
    'bracketopen([)': 'bracketopen',
    'comma(,)': 'comma',
    'equal(=)': 'equal'
}

DATASET_CONFIG = {
    'mka': {
        'num_segmentation_tries': 1000,
        'num_keystrokes': 30,
        'initial_step': 0.003,
        'min_stroke_length': 180,
        'steps': {
            'Lctrl': 0.002,
            'f': 0.003,
            'p': 0.003,
            'v': 0.0035,
        },
        'thresholds': {
            'Lctrl': 0.5,
            'f': 0.38,
            'p': 0.3,
            'v': 0.3,
        },
        'initial_threshold': 0.4,
        'before': 3000,
        'after': 5000,
        'last_strokes_to_skip': {
            'rshift': [-1],
            'lalt': [-1],
            'tab': [-1],
            '1': [-1],
            'b': [-1],
        },
        'keystrokes_to_skip': {
            'Lctrl': [13, 21],
            'm': [19],
            'n': [0],
            'o': [0],
            'ralt': [0],
            'u': [0, 12],
            'p': [0, 9, 11, 12, 13, 19],
            'f': [0],
            '3': [13],
            '4': [28],
            '5': [15],
            '6': [6],
            'e': [0],
            'lalt': [3],
            'lcmd': [0],
            'left': [0],
            's': [2],
            't': [14],
            'up': [12],
            'w': [27],
            'y': [17],
        },
    },
    'practical': {
        'num_segmentation_tries': 300,
        'num_keystrokes': 25,
        'initial_step': 0.006,
        'initial_threshold': 0.03,
        'before': 10000,
        'after': 10000,
        'min_stroke_length': 600,
        'keystrokes_to_skip': {
            'h': [0],
            '9': [0],
            '6': [0],
            'u': [0],
            '0': [0],
        },
        'last_strokes_to_skip': {
            'j': [-1],
            'n': [-1],
            'a': [-1],
            'c': [-1],
        },
    },
}